#!/bin/zsh

pkg list-all 2> /dev/null |
	awk '!/^Listing[.][.][.]$/' |
	awk -F/ '{ print $1 }' |
	fzf --multi --height=100% --preview-window='right:75%:wrap' \
		--preview 'pkg show {} 2> /dev/null |
		bat --color=always --pager=never --decorations=never --language=yaml'
