#!/bin/zsh

git config --list --show-origin |
	awk -F'[:\t]' --file <(<<- 'EOF'
		{
			file = $2; content = $3
			arr[file] = arr[file] "\n\t" content
		}
		END {
			for (file in arr) {
				system("zsh -c 'print -Df \\[%s] '" file)
				print arr[file]
			}
		}
	EOF
	) |
	bat --plain --language=ini # syntax highligthing
