#!/bin/zsh

git config --list --show-origin |
	awk -F'[:\t]' "$(<<- 'EOF'
		{
			key = $2; content = $3
			arr[key] = arr[key] "\n\t" content
		}
		END {
			for (key in arr) {
				system("zsh -c 'print -Df \\[%s] '" key)
				print arr[key]
			}
		}
		EOF
	)" |
	bat --plain --language=ini # syntax highligthing
