#!/bin/zsh
# <Docs> man zshexpn | less +/Parameter.Expansion.Flags '+/ (D|~)' </Docs>

# converts ~/ to absolute path
FILE=${~1}

# converts relative path to absolute since --no-symlinks
# only works as needed if path was already absolute
[[ ${FILE} == /* ]] || FILE=$PWD/$FILE

FILE=$(realpath --no-symlinks ${FILE})

# fail if path does does exist
[[ -e $FILE ]] || return 1

# converts absolute path to ~/
REPLY=${(D)FILE}
