#!/bin/zsh

local FC_ARGS=(
	-l # list
	-r # reverse
	1 # history starting from 1
)

# Filter duplicate commands
local AWK_ARG='{ line=$0; $1=""; if (!seen[$0]++) print line }'

local SET_COLOR
local RESET_COLOR=$'\e[m'
# zsh/rc.d/directory-history.zsh colors
if [[ $CURRENT_HISTFILE == $GLOBAL_HISTFILE ]]
then SET_COLOR=$'\e[33m' # Yellow
elif [[ $OTHER_HISTFILE == $GLOBAL_HISTFILE ]]
then SET_COLOR=$'\e[35m' # Magenta
else SET_COLOR=$'\e[2;3m' # dim and italic
fi

local SED_ARGS=(
	# Convert first column from right to left align
	--expression='s/^[[:space:]]*//'
	# Set styles for first column
	--expression='s/^[0-9]*/'${SET_COLOR}'&'${RESET_COLOR}'/'
)

local FZF_ARGS=(
	--ansi
	--scheme=history
	--bind=ctrl-r:'become(printf toggle)'
	# Exclude first field in search
	# This allows ^command searches
	# Use --with-nth to hide field
	--nth '2..'
)

fc "${FC_ARGS[@]}" |
awk "${AWK_ARG}" |
sed "${SED_ARGS[@]}" |
fzf "${FZF_ARGS[@]}" "$@"
