#!/bin/zsh

local KEY=$1 && shift
local ARGS=$@

if [[ $KEY == title ]]; then
	ARGS="${ARGS//:/ }"
	ARGS="${ARGS//[![:print:]]/ }"
fi

if [[ $KEY == clipboard ]]; then
	ARGS="$(base64 <<< "$ARGS")"
fi

local -A ESCAPE_CODES
ESCAPE_CODES=(
	blockcursor     '\e[1 q'
	underlinecursor '\e[3 q'
	barcursor       '\e[5 q'

	title     '\e]2;%s\a'
	clipboard '\e]52;%s\a'

	showcursor '\e[?25h'
	hidecursor '\e[?25l'

	upcursor    '\e[%sA'
	downcursor  '\e[%sB'
	rightcursor '\e[%sC'
	leftcursor  '\e[%sD'
	downline    '\e[%sE'
	upline      '\e[%sF'
)

printf "${ESCAPE_CODES[$KEY]}" "${ARGS}" > $TTY
