#!/bin/zsh

saveFile="${XDG_DATA_HOME}/zsh/lwd"

if [[ $1 == 'load' ]] && [[ -r "$saveFile" ]]; then
	local sessionPWD sessionOLDPWD
	{ read -rd '' sessionPWD && read -rd '' sessionOLDPWD; } < "$saveFile"
	[[ -d "$sessionOLDPWD" ]] && cd "$sessionOLDPWD"
	[[ -d "$sessionPWD" ]] && cd "$sessionPWD"
elif [[ $1 == 'save' ]]; then
	printf '%s\0%s' "$PWD" "$OLDPWD" > "$saveFile"
fi
