gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 20
  mainPanelSplitMode: horizontal
  showListFooter: false
  showNumstatInFilesView: true
  showPanelJumps: false
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  spinner:
      frames:
        - 'O'
        - 'oO'
        - 'ooO'
        - 'oooO'
      rate: 75
git:
  autoFetch: false
  autoRefresh: false
  paging:
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off
